### PR TITLE
Use the dev URLs for connect-src and img-src

### LINKED ISSUE #398: Addon cards are not being loaded on the addons blog
### Describe the problem and steps to reproduce it:

1. Load an addons blog article - https://addons-dev.allizom.org/blog/extension-starter-pack/
2.  Inspect its contents

### What happened?
The addon cards are not being loaded:
image

### What did you expect to happen?
Addon cards should be loaded like this:
image

### Anything else we should know?
This issue is currently reproducible only on AMO -dev.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes mozilla/addons-frontend#398

### CODE REVIEW

File: bin/deploy.sh [hunk 1]
```diff
@@ -33,6 +33,13 @@ if [ -z "$AMO_BASE_URL" ]; then
   exit 1
 fi
 
+# connect-src and img-src should be set to prod for prod and staging, but set
+# to dev for dev.
+CSP_CONNECT_IMG_SRC_PREFIX = "https://addons.mozilla.org"
+if [ "$AMO_BASE_URL" == "https://addons-dev.allizom.org" ]; then
+  CSP_CONNECT_IMG_SRC_PREFIX = "https://addons-dev.allizom.org"
+fi
```
Comment (willdurand) [inline bin/deploy.sh:41]: Nit

```suggestion
CSP_CONNECT_IMG_SRC_PREFIX="https://addons.mozilla.org"
if [ "$AMO_BASE_URL" == "https://addons-dev.allizom.org" ]; then
  CSP_CONNECT_IMG_SRC_PREFIX="https://addons-dev.allizom.org"
fi
```

**Review by willdurand — APPROVED** [review]
r+wc (maybe run `shellcheck` on this file)

File: bin/deploy.sh (hunk 1 above)
Comment (bobsilverberg) [reply bin/deploy.sh]: Thanks. Updated.
